version: "3.9"

services:
  nginx:
    env_file:
      - peerStat.env
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - java
    networks:
      - home
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - peerStat.env
    ports:
        - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  java:
    container_name: java
    image: openjdk:8-jre-alpine
    command: java -jar /app/PeerStat.jar
    ports:
      - "8080:8080"
    volumes:
      - ./java-app/PeerStat.jar:/app/PeerStat.jar:ro
    env_file:
      - peerStat.env
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    name: app-network

volumes:
  db-data:
